### ISSUE TITLE
getting FileNotFoundError in image_to_string

### ISSUE THREAD

**Issue by pawnzo90z** [madmaze/pytesseract#104]
my code 
#!/usr/bin/python3.6
from pytesseract import image_to_string
from PIL import Image
img = Image.open("/test.png")
text = image_to_string(img)
print(text)

output
Traceback (most recent call last):
  File "./tesser.py", line 5, in <module>
    text = image_to_string(img)
  File "/usr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py", line 215, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "/usr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py", line 162, in run_and_get_output
    run_tesseract(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytesseract/pytesseract.py", line 133, in run_tesseract
    proc = subprocess.Popen(command, **subprocess_args())
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tesseract': 'tesseract'

**Comment by int3l** [comment]
Hi @pawnzo90z 
Your problem is img = Image.open("**/test.png**")
/test,png means that your image is located in the root directory of your disc.
Apparently that's not the case.

If you want to open image in the same directory with the python script,
you need to pass either just **test.png** or **./test.png** (pay attention the the dot in front of the forward slash, which indicates the current working directory).

Closing the issue, since it's not directly related to the pytesseract.
Feel free to reopen and comment if you have any other issues.

**Comment by pawnzo90z** [comment]
No,It is actually stored in root directory

**Comment by int3l** [comment]
Yes, please check the PS section of my previous comment.
The actual problem is that pytesseract can't find the **tesseract** executable.
