### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jonathanrjpereira** [madmaze/pytesseract#107]
I installed it using `pip install pytesseract`

The package is located at `C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\Lib\site-packages\pytesseract` & contains the following files:
`1. pytesseract.py
2. test.png
3. test-european.png`

I am getting the following error:
`C:\Users\Jonathan\Documents\GitHub\Computer Vision Tests>python mnist.py --image 12416.png
Traceback (most recent call last):
  File "mnist.py", line 38, in <module>
    text = pytesseract.image_to_string(Image.open(filename))
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

There is no `Tesseract-OCR` folder in the `C:\\Program Files (x86)` directory.

**Comment by int3l** [comment]
Please follow the README Installation instructions. You need to install the Tesseract application itself in order to use pytesseract properly.
