### ISSUE TITLE
Error in program

### ISSUE THREAD

**Issue by zooeb** [madmaze/pytesseract#110]
Traceback (most recent call last):
  File "C:/Users/DEXTER/Desktop/de.py", line 5, in <module>
    print(pytesseract.image_to_string(img))
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by int3l** [comment]
You need to install the program tesseract. Please read the readme carefully.
This package has dependency of the Google Tesseract package.

If you have any other issues, feel free to reopen.

**Comment by zooeb** [comment]
Warning. Invalid resolution 0 dpi. Using 70 instead and blank text comes.
please help﻿
REPLY

**Comment by zooeb** [comment]
Thanks for the help . It worked
