### ISSUE TITLE
pytesseract AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by chan321** [madmaze/pytesseract#112]
I have just installed pytesseract on python 3.4  and while importing it I found this trackback

    Traceback (most recent call last):
      File "C:/Users/ROCKSTAR/Downloads/TRIVIA/getAnswers.py", line 6, in <module>
        import pytesseract
      File "C:\Python34\lib\site-packages\pytesseract\__init__.py", line 1, in <module>
        from .pytesseract import (
      File "C:\Python34\lib\site-packages\pytesseract\pytesseract.py", line 21, in <module>
    numpy_installed = True if find_loader('numpy') is not None else False
      File "C:\Python34\Lib\pkgutil.py", line 488, in find_loader
        return spec.loader
     AttributeError: 'NoneType' object has no attribute 'loader'

    Process finished with exit code 1`

**Comment by int3l** [comment]
Hi @chan321,
If you can, try to update your python version. From what I found - it's a python 3.4.1 specific bug.
The code itself follows the documentation.
