### ISSUE TITLE
No Such file or directory

### ISSUE THREAD

**Issue by Padalingam** [madmaze/pytesseract#117]
Hi All,
I am using mac machine to get text from the image. I installed pytesseract and i didn't get any installation error. when i run the following code i got the error
user$  python ocrdection.py 
Traceback (most recent call last):
  File "ocrdection.py", line 44, in <module>
    print pytesseract.image_to_string(Image.open('test.png'))
  File "/Users/padalingam/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "/Users/padalingam/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "/Users/padalingam/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "/Users/padalingam/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/padalingam/anaconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Anybody have a look into it

**Comment by int3l** [comment]
You should install the Tesseract executable in order to use pytesseract - please refer to the README documentation for more information how to install it under Mac OS.
