### ISSUE TITLE
Deployment on iis server OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by ionspicica** [madmaze/pytesseract#123]
Hello. Everything works perfectly in development, but the error appears in the production on the IIS server  `  File "C:\inetpub\wwwroot\cmb\env\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python36\Lib\subprocess.py", line 665, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python36\Lib\subprocess.py", line 903, in _get_handles
    c2pwrite = _winapi.GetStdHandle(_winapi.STD_OUTPUT_HANDLE)
OSError: [WinError 6] The handle is invalid
`

**Comment by int3l** [comment]
Please be sure that you have execution rights from inside the production server.
You can do a simple test of calling the tesseract executable by itself with some test img via the subprocess medule. This will tell you if the problem is related to permissions/access restrictions.

**Comment by ionspicica** [comment]
I changed this line:
`proc = subprocess.Popen(command, stderr=subprocess.PIPE)`
with this line:
`proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.DEVNULL)`
works both in production and in development

**Comment by int3l** [comment]
Oh, sorry, can you test the latest version of pytesseract from github, because it already includes that code?
it is pytesseract 0.2.2. You can try to install it directly from github (check the README file for instructions).

**Comment by ionspicica** [comment]
I tested, it works. Thanks!

**Comment by shahla69** [comment]
hi
Would you mind telling me where my problem is ?
I run a Python file, but it does not run full and ends in the middle of the run!!

C:\Users\Hatami\Desktop\test\AdaptiveTrafficSignalControl-master>python four_int
ersects.py
Traceback (most recent call last):
  File "four_intersects.py", line 403, in <module>
    main()
  File "four_intersects.py", line 395, in main
    fixed_control_run(10)
  File "four_intersects.py", line 168, in fixed_control_run
    game_env.reset()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\site-packages
\gym\wrappers\time_limit.py", line 44, in reset
    return self.env.reset()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\site-packages
\gym\envs\toy_text\four_intersects_env.py", line 121, in reset
    self.start_sumo()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\site-packages
\gym\envs\toy_text\four_intersects_env.py", line 108, in start_sumo
    traci.start(self.sumo_cmd)
  File "C:\Program Files (x86)\DLR\Sumo\tools\traci\__init__.py", line 82, in st
art
    sumoProcess = subprocess.Popen(cmd + ["--remote-port", str(port)])
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\subprocess.py
", line 594, in __init__
    _cleanup()
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\subprocess.py
", line 205, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Users\Hatami\AppData\Local\Programs\Python\Python36\lib\subprocess.py
", line 1027, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] The handle is invalid

python3.6
windows 7
 please help me
