### ISSUE TITLE
OSError: [Errno 2] No such file or directory error

### ISSUE THREAD

**Issue by radzhome** [madmaze/pytesseract#13]
The image seems to open, but then when I run image_to_string, it throws an exception:

```
>>> i = Image.open('test.png')
>>> print(pytesseract.image_to_string(i))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 161, in image_to_string
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by radlws** [comment]
So works now after installing the ubuntu package:

    sudo apt-get install tesseract-ocr

Can a full install be done via pip?

**Comment by madmaze** [comment]
Not that I am aware of, but we should probably fail more gracefully.
Perhaps detect which distro and suggest installing it.

**Comment by jiakechong1991** [comment]
I am MAC,when have the program,I use "sudo brew install tesseract",now I am OK,please try

**Comment by dorajam** [comment]
@radzhome Thanks so much for this, it perfectly fixed what I have struggled to figure out for days now... 👍

**Comment by mattcanavan** [comment]
Thank you for the tip @radzhome! 

@madmaze do you think you could add their blurb to the README for those less savvy?
