### ISSUE TITLE
environment can only contain strings

### ISSUE THREAD

**Issue by Ads5740** [madmaze/pytesseract#137]
Hi Team,

I seem to be getting this error
```
Traceback (most recent call last):
  File "test.py", line 62, in <module>
    result = pytesseract.image_to_string(image).encode("utf-8")
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 286, in
image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 194, in
run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 165, in
run_tesseract
    proc = subprocess.Popen(command, **subprocess_args())
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

I'm running 0.2.2 version on Python 2.7.13 on windows, not sure why this is now coming up.

my test code is simple:
```
test_file = os.path.join('c:' + os.sep, 'Python27','Lib','site-packages','pytesseract', 'test.png')
image = Image.open(test_file)
result = pytesseract.image_to_string(image).encode("utf-8")
print result
```

**Comment by Ads5740** [comment]
Cancel, seems like an environmental variable issue, added Tesseract to the path and all good

**Comment by Ads5740** [comment]
Update:
Added path to environment variable.

The ran a few commands:
- from the Pytesseract package folder:
```
C:\Python27\Lib\site-packages\pytesseract>python pytesseract.py test.png
This is a lot of 12 point text to test the
cor code and see if it works on all types
of file format.

The quick brown dog jumped over the
lazy fox. The quick brown dog jumped
over the lazy fox. The quick brown dog
jumped over the lazy fox. The quick
brown dog jumped over the lazy fox.

C:\Python27\Lib\site-packages\pytesseract>python pytesseract.py test-european.jp
g
Traceback (most recent call last):
  File "pytesseract.py", line 369, in <module>
    main()
  File "pytesseract.py", line 362, in main
    print(image_to_string(Image.open(filename), lang=lang))
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u201d' in position
 150: character maps to <undefined>
```

However, if I try to call Pytesseract form the script above:
```
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    result = pytesseract.image_to_string(image)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 286, in
image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 194, in
run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 165, in
run_tesseract
    proc = subprocess.Popen(command, **subprocess_args())
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

**Comment by int3l** [comment]
Strange behavior.
Workarounds:
- Update to [Python 2.7.15](https://www.python.org/downloads/release/python-2715/) (latest release as of today)
- Check your ```os.environ```, because it seems that there is some key/value in this dictionary that's not a standard python string.

**Comment by Ads5740** [comment]
Hi Int3l, 
I found the issue:
As you said in the os.environ.
It seems to have this:
```
'PROGRAMFILES': 'C:\\Program Files (x86)',
 'PROCESSOR_REVISION': '4501',
 'PATH': u'C:\\Program Files (x86)\\ImageMagick-6.9.10-Q16;C:\\Python27\\;
```

I'm not sure where the "u'" is coming from, if I removethis and hard code the os.environ in the pytesseract.py it works

**Comment by Ads5740** [comment]
Hi int3l,

You're a genius, that worked, no idea where it came from, thanks for your help, much appreciated
