### ISSUE TITLE
image.split() causes error

### ISSUE THREAD

**Issue by amoghbl1** [madmaze/pytesseract#15]
img = Image.open('./imgs/SAM_0190.JPG')
pytesseract.image_to_string(img)
Causes:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 143, in image_to_string
    if len(image.split()) == 4:
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1497, in split
    if self.im.bands == 1:
AttributeError: 'NoneType' object has no attribute 'bands'

PIL version: 1.1.7
pytesseract: 0.1.6

**Comment by madmaze** [comment]
please see my comment attached to your pull request.
