### ISSUE TITLE
-oem 1 propting cube error

### ISSUE THREAD

**Issue by mhenrichsen** [madmaze/pytesseract#157]
HI,

When using `-oem 1` I get the following error:

> Traceback (most recent call last):
  File "/Users/madsgadehenrichsen/Desktop/ocr/udtraek_tekst.py", line 51, in <module>
    ocr.append_tekst_og_metadata(img_path_slash + jpg)
  File "/Users/madsgadehenrichsen/Desktop/ocr/ocr.py", line 50, in append_tekst_og_metadata
    text.append(ocr(sti))
  File "/Users/madsgadehenrichsen/Desktop/ocr/ocr.py", line 37, in ocr
    text = pytesseract.image_to_string(im, config=config)
  File "/Users/madsgadehenrichsen/.local/share/virtualenvs/ocr/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 294, in image_to_string
    return run_and_get_output(*args)
  File "/Users/madsgadehenrichsen/.local/share/virtualenvs/ocr/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 202, in run_and_get_output
    run_tesseract(**kwargs)
  File "/Users/madsgadehenrichsen/.local/share/virtualenvs/ocr/lib/python3.7/site-packages/pytesseract/pytesseract.py", line 178, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (-6, 'Cube ERROR (CubeRecoContext::Load): unable to read cube language model params from /usr/local/Cellar/tesseract/3.05.02/share/tessdata/dan.cube.lm Cube ERROR (CubeRecoContext::Create): unable to init CubeRecoContext object init_cube_objects(false, &tessdata_manager):Error:Assert failed:in file tessedit.cpp, line 210')

I've tried using -l eng but it gives the same error.

**Comment by int3l** [comment]
This error is generated by **tesseract** itself and is not **pytesseract** specific. The issue itself is related to missing files - please take a look at: [unable to open Cube language model params for hindi Language in tesseract](https://stackoverflow.com/questions/35403070/unable-to-open-cube-language-model-params-for-hindi-language-in-tesseract)
