### ISSUE TITLE
Pytesseract crashes

### ISSUE THREAD

**Issue by parayamelo** [madmaze/pytesseract#176]
Hi,
I am running pytesseract on Kubuntu 18.04 with python 3, and it crashes (computer reboots) when I do

import os
from PIL import Image
import pytesseract
texto = pytesseract.image_to_string(Image.open('norm.jpg'), lang='spa', config='--psm 6')

I tried it without lang and config, and it still crashes. What is strange is that on my laptop, it runs fine. The rebooting happens on my desktop.

I tried to match the python modules used on my laptop on my desktop, but I still get the same error.

Do you know how I can fix this?

Thank you.

**Comment by int3l** [comment]
You can try to use the tesseract command itself with the same arguments.
If the crash is still present - it might be a tesseract related issue.

**Comment by parayamelo** [comment]
Hi @int3l ,

I installed tesseract from github. It crashes with option --psm 6
Will ask in the tesseract group
Will report back, thank you!

**Comment by ShubhamBirhade1** [comment]
hi i am facing the followinng error
how should i solve this error

Traceback (most recent call last):
  File "C:/Users/Admin/demo5.py", line 11, in <module>
    result= pytesseract.image_to_string(img)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 347, in image_to_string
    }[output_type]()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 346, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 257, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\pytesseract\pytesseract.py", line 233, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (3221225477, '')

**Comment by int3l** [comment]
What is the version of your OS and Tesseract install? And is it 32 or 64 bit.
This is not a pytesseract specific error, but an external one from Tesseract.

**Comment by ShubhamBirhade1** [comment]
I am using windows 10
64 bit os
