### ISSUE TITLE
WindowsError: [Error 2]

### ISSUE THREAD

**Issue by omytea** [madmaze/pytesseract#18]
I ran the compiled execution file under windows7 python 2.7. And I got this error

c:\temp>pytesseract captcha.png
Traceback (most recent call last):
  File "C:\Python27\Scripts\pytesseract-script.py", line 9, in <module>
    load_entry_point('pytesseract==0.1.6', 'console_scripts', 'pytesseract')()
  File "build\bdist.win32\egg\pytesseract\pytesseract.py", line 187, in main
  File "build\bdist.win32\egg\pytesseract\pytesseract.py", line 161, in image_to
_string
  File "build\bdist.win32\egg\pytesseract\pytesseract.py", line 94, in run_tesse
ract
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]

**Comment by madmaze** [comment]
Do you have tesseract-ocr installed and is the executable in your PATH environment variable?
if tesseract-ocr is not in your path, edit this: https://github.com/madmaze/pytesseract/blob/master/src/pytesseract.py#L60

In the future there should probably be a cmd line option to set the location of tesseract

**Comment by tj-mueller** [comment]
I have a similar problem here, also using python 27 und Windows 7

The error reads as follows

Traceback (most recent call last):
  File "C:\Users\Internet\Desktop\OCR-Projekt\OCR.py", line 30, in <module>
    print image_to_string(Image.open("C:\Users\Internet\Desktop\OCR-Projekt\im_name.png"))
  File "C:\Program Files (x86)\Python27\lib\site-packages\pytesseract\pytesseract.py", line 161, in image_to_string
    config=config)
  File "C:\Program Files (x86)\Python27\lib\site-packages\pytesseract\pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Program Files (x86)\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] 

tesseract 3.02.02 was installed with its original name and set in PATH. I am able to call it in cmd with and without administration rights.
Instead of the original PIL, pillow was installed

**Comment by madmaze** [comment]
@tj-mueller could you try to give set tesseract_cmd to the full path of your tesseract binary and try it again?

**Comment by tj-mueller** [comment]
@madmaze changing tesseract_cmd did not resolve the problem. Neither
C:\Program Files (x86)\Tesseract-OCR\tesseract.exe
nor
C:\Program Files (x86)\Tesseract-OCR\
worked so far.

**Comment by madmaze** [comment]
hmm i'll try to get my hands on some windows, but that might take a little while

**Comment by omytea** [comment]
@madmaze It is my fault that not giving the right path. Thanks for answering

**Comment by aristotll** [comment]
I have the same problem

**Comment by ChaoWing** [comment]
CMD window is worked normal, but pytesseract is failed.
`Traceback (most recent call last):
  File "D:/PycharmProjects/net.bjxueche.haijia/CoreImage.py", line 79, in <module>
    text = image_to_string(image=image2, boxes=True)
  File "D:\mysoft\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 161, in image_to_string
    config=config)
  File "D:\mysoft\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "D:\mysoft\Python\Python35\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "D:\mysoft\Python\Python35\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。`

**Comment by DSdavidDS** [comment]
Currently getting the same error. Running on Python3 with Pillow.

**Comment by chrispwns** [comment]
Chiming in to say this issue is happening to me as well. Windows 10 64-bit.

tesseract works in the command line like this:
![tess](https://cloud.githubusercontent.com/assets/10478216/21694732/42ea1808-d34c-11e6-878e-2d2546d8b968.png)

but, while I can open an image with PIL, the moment it's passed into pytesseract I get
FileNotFoundError: [Errno 2] No such file or directory: '/images/test-text.png'

**Comment by int3l** [comment]
Please use the appropriate tesseract 3.x or 4.x versions.
When you have errors with forward slashes on Windows, this means that your configuration is messed up or your tesseract version is not compiled correctly.

If you have any additional comments, please feel free to reopen the issue.
