### ISSUE TITLE
image_to_string error: Unsupported image format/type

### ISSUE THREAD

**Issue by colonder** [madmaze/pytesseract#220]
I work on Linux (Kubuntu 18.04 LTS x64). Created a fresh Anaconda environment by using the following commands:
```
conda create --name test python=3.6
conda activate test
conda install numpy
conda install -c conda-forge pytesseract
```
This left me with the following packages installed
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
blas                      1.0                         mkl  
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
flake8                    3.7.8                    py36_1    conda-forge
flake8-polyfill           1.0.2                      py_0    conda-forge
flake8-quotes             2.1.0                      py_0    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
importlib_metadata        0.18                     py36_0    conda-forge
intel-openmp              2019.4                      243  
jpeg                      9c                h14c3975_1001    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
more-itertools            7.2.0                      py_0    conda-forge
ncurses                   6.1                  he6710b0_1  
numpy                     1.16.4           py36h7e9f1db_0  
numpy-base                1.16.4           py36hde5b4d6_0  
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pep8-naming               0.8.2                      py_0    conda-forge
pillow                    5.3.0           py36h00a061d_1000    conda-forge
pip                       19.1.1                   py36_0  
pluggy                    0.12.0                     py_0    conda-forge
py                        1.8.0                      py_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pytesseract               0.2.8                      py_0    conda-forge
pytest                    5.0.1                    py36_0    conda-forge
python                    3.6.9                h265db76_0  
readline                  7.0                  h7b6447c_5  
setuptools                41.0.1                   py36_0  
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.4                   py36_0  
xz                        5.2.4                h14c3975_4  
zipp                      0.5.2                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```
Now, when in the environment if I type
```
>>> import numpy as np
>>> a = np.empty((10, 10))
>>> import pytesseract as pyt
>>> pyt.image_to_string(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kuba/.anaconda3/envs/test/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 341, in image_to_string
    }[output_type]()
  File "/home/kuba/.anaconda3/envs/test/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 340, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/kuba/.anaconda3/envs/test/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 238, in run_and_get_output
    temp_name, input_filename = save_image(image)
  File "/home/kuba/.anaconda3/envs/test/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 157, in save_image
    raise TypeError('Unsupported image format/type')
TypeError: Unsupported image format/type
```
The method works just fine when pytesseract is installed via pip (it installs version 0.2.7)

**Comment by int3l** [comment]
This is a regression from 0.2.7 to 0.2.8 - and it is related to the fact that the images converted from np arrays, doesn't have proper image.format. Needs a fix.
