### ISSUE TITLE
pytesseract ko on image_to_string

### ISSUE THREAD

**Issue by julienb29** [madmaze/pytesseract#29]
Hello,

*_My source is the following : 
*_
`import pytesseract as pt
import Image as im
from PIL import Image as PILim
# print pt.image_to_string(im.open("t.png"))

img = im.open('t.png')
img.load()
print pt.image_to_string(img)`

**And I have:**

Traceback (most recent call last):
  File "D:\Fichier\Eclipse\Test__init__.py", line 28, in <module>
    print pt.image_to_string(img)
  File "build\bdist.win32\egg\pytesseract\pytesseract.py", line 161, in image_to_string
  File "build\bdist.win32\egg\pytesseract\pytesseract.py", line 94, in run_tesseract
  File "C:\Python27\lib\subprocess.py", line 709, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
WindowsError: [Error 2] Le fichier spécifié est introuvable

Do you have any idea?

Thanks in advance.

**Comment by ashimaathri** [comment]
You have to install the `tesseract` package for this - https://github.com/tesseract-ocr/tesseract/wiki#installation
