### ISSUE TITLE
tesseract multiple languages error

### ISSUE THREAD

**Issue by alirezashamohammadi** [madmaze/pytesseract#311]
import cv2
import pytesseract

pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
img = cv2.imread('farsi.PNG')
img = cv2.resize(img, None,fx=10,fy=10)
gray=cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
adaptive_threshold = cv2.adaptiveThreshold(gray, 255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,11,2)
text=pytesseract.image_to_string(gray,lang='fas')
#text=pytesseract.image_to_boxes(gray)
print(text)
cv2.imshow("gray",gray)
cv2.imshow("img",img)
cv2.waitKey(0)

error:

Traceback (most recent call last):
  File "C:/Users/Alireza/PycharmProjects/untitled19/venv/farsi.py", line 8, in <module>
    print(pytesseract.image_to_string(Image.open('farsi.PNG'), lang='fas'))
  File "C:\Users\Alireza\PycharmProjects\untitled19\venv\lib\site-packages\pytesseract\pytesseract.py", line 370, in image_to_string
    return {
  File "C:\Users\Alireza\PycharmProjects\untitled19\venv\lib\site-packages\pytesseract\pytesseract.py", line 373, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\Alireza\PycharmProjects\untitled19\venv\lib\site-packages\pytesseract\pytesseract.py", line 282, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\Alireza\PycharmProjects\untitled19\venv\lib\site-packages\pytesseract\pytesseract.py", line 258, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (3221225477, '')

Process finished with exit code 1

**Comment by int3l** [comment]
Do you have the `fas` Persian language files installed? It might not be installed by default.
This seems to be tesseract specific issue. Can you try to run tesseract itself with the appropriate options and check the error.
Example command:
```bash
tesseract --list-langs
```
