### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by liebig** [madmaze/pytesseract#316]
I am trying to get pytesseract to run on a Windows 10 system but unfortunately always get the following error log:

```Traceback (most recent call last):
  File "C:\Users\Marc\PycharmProjects\test\venv\lib\site-packages\pytesseract\pytesseract.py", line 27, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Marc\PycharmProjects\test\main.py", line 15, in <module>
    import pytesseract
  File "C:\Users\Marc\PycharmProjects\test\venv\lib\site-packages\pytesseract\__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "C:\Users\Marc\PycharmProjects\test\venv\lib\site-packages\pytesseract\pytesseract.py", line 29, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'

Process finished with exit code 1
```

**Comment by liebig** [comment]
Okay I must have messed up my installed pip packages. Created a new Python project, installed pytesseract and everything works.

**Comment by sudhan-c** [comment]
may i know how u closed the error i am having the same issue..
Traceback (most recent call last):
  File "pytesseract.py", line 27, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 68, in <module>
    from PIL import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pytesseract.py", line 29, in <module>
    import Image
ModuleNotFoundError: No module named 'Image'

**Comment by int3l** [comment]
Hi @sudhan-c -- it seems that your setup/virtual environment might have some kind of problem.
If you use the latest version and install it in isolated virtual environment, there should be no problems.
You can find more information how to setup clean install in the docs.

**Comment by halvomez** [comment]
hi, it's ok with version 0.3.7, but 0.3.8 crash with same error

`from .pytesseract import ALTONotSupported
      File "/tmp/pip-install-wt3k8kh5/pytesseract/pytesseract/pytesseract.py", line 28, in <module>
        import Image
    ModuleNotFoundError: No module named 'Image'
`

**Comment by int3l** [comment]
Can you try installing the `Pillow` package as a workaround? It is very strange that you have this issue for your environment, since all project tests pass.

**Comment by eddiezab** [comment]
While this issue is closed, I've observed something interesting -- but I don't know where the breakdown is. I'm installing pytesseract (no version specified) as in a requirements.txt

`
python3 -m venv /tmp/envdir
. /tmp/envdir/bin/activate
pip install -r requirements.txt
`

Adding Pillow prior to pytesseract in the requirements.txt appears to do _something_, but I still get the issue as above. However, if, and only if, I explicitly run `pip install Pillow` (with or without it being in the requirements.txt) do I get pytesseract to install.

**Comment by ChipmunkV** [comment]
Steps to reproduce:
```
docker run -it --rm ubuntu:focal bash
apt -y update
apt -y install python3-pip
pip3 install pytesseract
```
Something is wrong with pytesseract  package dependencies.

**Comment by liebig** [comment]
Okay, since this problem affects several people, I am reopening this issue.

**Comment by int3l** [comment]
Thank you very much for reporting this. I will have to investigate why it suddenly stated failing -- I suspect pip.

**Comment by int3l** [comment]
Ok, so Pillow requires python 3.7 or higher, because python 3.6 is End of Life.
I updated the current CI setup for that. Can't test the docker reproduction steps right now, because I am on a restricted computer.
But you can try the following to confirm that the latest master is working:

```bash
docker run -it --rm ubuntu:focal bash
apt -y update
apt -y install python3-pip git
pip3 install -U git+https://github.com/madmaze/pytesseract.git
```

If this works, I can create a new release.

**Comment by ChipmunkV** [comment]
Same error (sorry, haven't included it the first time).

Python 3.8.10

```
/# pip3 install -U git+https://github.com/madmaze/pytesseract.git
Collecting git+https://github.com/madmaze/pytesseract.git
  Cloning https://github.com/madmaze/pytesseract.git to /tmp/pip-req-build-fzd_0juj
  Running command git clone -q https://github.com/madmaze/pytesseract.git /tmp/pip-req-build-fzd_0juj
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fzd_0juj/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fzd_0juj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-fzd_0juj/pip-egg-info
         cwd: /tmp/pip-req-build-fzd_0juj/
    Complete output (42 lines):
    Traceback (most recent call last):
      File "/tmp/pip-req-build-fzd_0juj/pytesseract/pytesseract.py", line 26, in <module>
        from PIL import Image
    ModuleNotFoundError: No module named 'PIL'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-fzd_0juj/setup.py", line 4, in <module>
        setup()
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 701, in parse_config_files
        parse_configuration(self, self.command_options,
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 121, in parse_configuration
        meta.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 426, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 399, in parse_section
        self[name] = value
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 184, in __setitem__
        value = parser(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 515, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 349, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 848, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-req-build-fzd_0juj/pytesseract/__init__.py", line 2, in <module>
        from .pytesseract import ALTONotSupported
      File "/tmp/pip-req-build-fzd_0juj/pytesseract/pytesseract.py", line 28, in <module>
        import Image
    ModuleNotFoundError: No module named 'Image'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by int3l** [comment]
Hmm, I literally just ran this thru CI testing and it worked without a problem.
From what I can see, you are not using virtualenv.
Can you test if it works inside a virtualenv:

```bash
virtualenv venv
. venv/bin/activate
pip install -U git+https://github.com/madmaze/pytesseract.git
```

Also, this error is from within a fresh Ubuntu focal container, right?

**Comment by ChipmunkV** [comment]
Updating either pip or setuptools solves the problem. Versions that don't work: pip 20.0.2, setuptools 45.2.0. Versions that do: pip 21.3.1, setuptools 60.5.0.

**Comment by int3l** [comment]
Yeah ... It seems that Pillow depends on newer versions of those tools, for reference they even include the update step in the [Pillow - Installation docs](https://pillow.readthedocs.io/en/stable/installation.html#basic-installation)

**Comment by int3l** [comment]
The new pytesseract version should fix this for now.

**Comment by YashitM** [comment]
> Updating either pip or setuptools solves the problem. Versions that don't work: pip 20.0.2, setuptools 45.2.0. Versions that do: pip 21.3.1, setuptools 60.5.0.

[ChipmunkV](https://github.com/ChipmunkV) thanks for that. Updating these packages worked!
