### ISSUE TITLE
Python3 linux : f"{tesseract_cmd} is not installed or it's not in your PATH.

### ISSUE THREAD

**Issue by pristis** [madmaze/pytesseract#338]
I have file called "test.py" on my Raspberry 

```
from PIL import Image
import pytesseract

print(pytesseract.image_to_string(Image.open('test.png')))
```

After run it with Python3 I see the error.

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import pytesseract
  File "/home/pi/.local/lib/python3.5/site-packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "/home/pi/.local/lib/python3.5/site-packages/pytesseract/pytesseract.py", line 89
    f"{tesseract_cmd} is not installed or it's not in your PATH."
                                                                ^
SyntaxError: invalid syntax

```

I saw another issue #335 (about Windows), but there are only advice to using python3. Well, it doesn't help for me on linux.

I will appreciate some help.

**Comment by int3l** [comment]
This error means that you have an old version of Python.  You will need to install/upgrade python to  version 3.6+
