### ISSUE TITLE
OSD not working

### ISSUE THREAD

**Issue by casperbh96** [madmaze/pytesseract#381]
Hello, I am trying to use the orientation detection from Tesseract using your wrapper.

Can you please help me fix this issue?

From `tesseract test1.png - --psm 0`, I get the correct output:

```
Page number: 0
Orientation in degrees: 270
Rotate: 90
Orientation confidence: 8.04
Script: Latin
Script confidence: 4.69
```

When I use a similar command

```
from PIL import Image
print(pytesseract.image_to_osd(Image.open('test1.png')))
```

It produces

```
Traceback (most recent call last):
  File "read_rotated_pages.py", line 154, in <module>
    print(pytesseract.image_to_osd(Image.open('test1.png')))
  File "C:\Users\cbh037\Miniconda3\envs\invoice\lib\site-packages\pytesseract\pytesseract.py", line 539, in image_to_osd
    return {
  File "C:\Users\cbh037\Miniconda3\envs\invoice\lib\site-packages\pytesseract\pytesseract.py", line 542, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\cbh037\Miniconda3\envs\invoice\lib\site-packages\pytesseract\pytesseract.py", line 287, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\cbh037\Miniconda3\envs\invoice\lib\site-packages\pytesseract\pytesseract.py", line 263, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v5.0.0-alpha.20210506 with Leptonica UZN file C:\\Users\\cbh037\\AppData\\Local\\Temp\\tess_jonwi5da loaded. Estimating resolution as 242 UZN file C:\\Users\\cbh037\\AppData\\Local\\Temp\\tess_jonwi5da loaded. Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')
```

**Comment by int3l** [comment]
Hi @casperbh96 
Can you try to pass the raw image like this: `pytesseract.image_to_osd('test1.png')` - which will skip the image conversion in python.
I guess that the image conversion strips some of the image data and this is why you get the error.
