### ISSUE TITLE
PermissionError: [WinError 5] Accessed denied

### ISSUE THREAD

**Issue by jungjinki** [madmaze/pytesseract#395]
I'm trying to do test run and the code below produce the following error :
       PermissionError: [WinError 5] Accessed denied.
Any help would be appreciated to find why it occurs. 
Thanks for your help in advance.

----------- test code -----------
try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract

pytesseract.pytesseract.tesseract_cmd = r'D:\E\c2.codeLab\python\tesseract\pytesseract-master\pytesseract'
print(pytesseract.image_to_string(Image.open('test.png')))

--------- full error message -------

       D:\E\c2.codeLab\python\tesseract\pytesseract-master\tests>python t2.py
       Traceback (most recent call last):
         File "D:\E\c2.codeLab\python\tesseract\pytesseract-master\tests\t2.py", line 8, in <module>
           pytesseract.image_to_string(Image.open('test.png'))
         File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytesseract\pytesseract.py", line 413, in image_to_string
           return {
         File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytesseract\pytesseract.py", line 416, in <lambda>
           Output.STRING: lambda: run_and_get_output(*args),
         File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytesseract\pytesseract.py", line 284, in run_and_get_output
           run_tesseract(**kwargs)
         File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytesseract\pytesseract.py", line 255, in run_tesseract
           raise e
         File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pytesseract\pytesseract.py", line 252, in run_tesseract
           proc = subprocess.Popen(cmd_args, **subprocess_args())
         File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
           self._execute_child(args, executable, preexec_fn, close_fds,
         File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
           hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
       PermissionError: [WinError 5] Accessed denied.

**Comment by OdeMillington** [comment]
pytesseract.pytesseract.tesseract_cmd should be assigned to the executable of tesseract.

**Comment by jungjinki** [comment]
I am trying to figure out the path for Tesseract executable. 
The only choice seems  <...>/pytesseract-master/pytesseract
where I find "__init__.py" and  "pytesseract.py". 

So I put as below: 
  
pytesseract.pytesseract.tesseract_cmd = r'D:\E\c2.codeLab\python\tesseract\pytesseract-master\pytesseract'

is there any other path that I am missing ?

![image](https://user-images.githubusercontent.com/22660617/140411331-f423ba05-82cf-4892-ac64-126f0c0a8a77.png)
