### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guess\\AppData\\Local\\Temp\\tess_gtrqc8za.hocr'

### ISSUE THREAD

**Issue by Agkhan625** [madmaze/pytesseract#529]
pytesseract.pytesseract.tesseract_cmd = r'C:\Users\guess\AppData\Local\Programs\Tesseract-OCR\tesseract.exe'
    # custom_dir = r'C:/Users/guess/Documents/custom/tessdata_best-4.1.0'
    custom_config = r'--tessdata-dir "C:\Users\guess\Documents\custom\tessdata"'
    # custom_config = f'--psm 3 --oem 3'
    hocr = pytesseract.image_to_pdf_or_hocr(new_img, extension='hocr', lang=lang, config=custom_config)

error:
C:\Users\guess\PycharmProjects\pythonProject3\.venv\Scripts\python.exe C:\Users\guess\PycharmProjects\pythonProject3\bot.py 
Cause exception while process update id=855272136 by bot id=6944438024
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guess\\AppData\\Local\\Temp\\tess_gtrqc8za.hocr'
Traceback (most recent call last):
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\bot.py", line 97, in process_photo
    hocr = pytesseract.image_to_pdf_or_hocr(new_img, extension='hocr', lang=lang, config=custom_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\pytesseract\pytesseract.py", line 446, in image_to_pdf_or_hocr
    return run_and_get_output(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guess\PycharmProjects\pythonProject3\.venv\Lib\site-packages\pytesseract\pytesseract.py", line 290, in run_and_get_output
    with open(filename, 'rb') as output_file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guess\\AppData\\Local\\Temp\\tess_gtrqc8za.hocr'

**Comment by stefan6419846** [comment]
This has been fixed in version 0.3.11, which is not yet available on PyPI. Please install from GitHub or pass the additional config `-c tessedit_create_hocr=1`.

**Comment by Agkhan625** [comment]
Thank you ..it worked

**Comment by Agkhan625** [comment]
.
