### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Xonshiz** [madmaze/pytesseract#59]
So, I just installed this lib and I'm using Python 3.5 on windows 7.

My code that's giving the error

```
myText2 = image_to_string(Image.open("myImage.png"))
```

Error that I'm getting : 

```
Traceback (most recent call last):
  File "F:/Competitions/Donations/Scrapping.py", line 113, in <module>
    Scrapping()
  File "F:/Competitions/Donations/Scrapping.py", line 58, in __init__
    myText2 = image_to_string(Image.open("captcha.png"))
  File "C:\Users\User Name\AppData\Roaming\Python\Python35\site-packages\pytesseract\pytesseract.py", line 163, in image_to_string
    errors = get_errors(error_string)
  File "C:\Users\User Name\AppData\Roaming\Python\Python35\site-packages\pytesseract\pytesseract.py", line 111, in get_errors
    error_lines = tuple(line for line in lines if line.find('Error') >= 0)
  File "C:\Users\User Name\AppData\Roaming\Python\Python35\site-packages\pytesseract\pytesseract.py", line 111, in <genexpr>
    error_lines = tuple(line for line in lines if line.find('Error') >= 0)
TypeError: a bytes-like object is required, not 'str'
```

I went through all the previous Issues regarding this matter and I've updated my tesseract version to 4.0 and have all the trained files available. But, I'm getting this error, what's the issue and how can it be fixed?

Older issue  : https://github.com/madmaze/pytesseract/issues/32

I even tried [this step mentioned in SO answer](https://stackoverflow.com/questions/41368728/typeerror-a-bytes-like-object-is-required-not-str-in-python-3-5-2-and-pytess/41368800), but after this, I have the same problem as OP. The error changes to

```
Traceback (most recent call last):
  File "F:/Competitions/Donations/Scrapping.py", line 113, in <module>
    Scrapping()
  File "F:/Competitions/Donations/Scrapping.py", line 58, in __init__
    myText2 = image_to_string(Image.open("captcha.bmp"))
  File "C:\Users\User Name\AppData\Roaming\Python\Python35\site-packages\pytesseract\pytesseract.py", line 164, in image_to_string
    raise TesseractError(status, errors)
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\eng.traineddata')
```

**Comment by int3l** [comment]
Please download the latest version from github, because the current version of this package is older in the pypi repository.

Also for the tesseract error, please check the Usage section of the README.

**Comment by int3l** [comment]
Ok, we have the new updated 0.1.7 version, so you can updated it via pip.
Closing this one, since the errors are already addressed either via the new version or the documentation.
