### ISSUE TITLE
PremissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by diyali03** [madmaze/pytesseract#62]
I am using OSx with python 3.6

Here is my code:

```
try:
    import Image
except:
    from PIL import Image
import pytesseract

pytesseract.pytesseract.tesseract_cmd = '/usr/local/Cellar/tesseract/3.05.01/'

import cv2

img = cv2.imread('case_2.png')
img = Image.fromarray(img)
print(pytesseract.image_to_string(img, lang='chi_sim'))
```

But it outputted an error:

```
Traceback (most recent call last):
  File "/Users/Dylan/Documents/GitHub/Genedock/ocr_framework/tempfyllslkgxc.py", line 13, in <module>
    print(pytesseract.image_to_string(Image.open('case_2.png'), lang='chi_sim'))
  File "/Users/Dylan/anaconda/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 122, in image_to_string
    config=config)
  File "/Users/Dylan/anaconda/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "/Users/Dylan/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/Dylan/anaconda/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```
I search all of the StackOverflow, but in vain.

So hope you can help me as soon as possible.

**Comment by int3l** [comment]
Your error is on this line:
`pytesseract.pytesseract.tesseract_cmd = '/usr/local/Cellar/tesseract/3.05.01/'`

You should point the tesseract_cmd to the exact path of the **tesseract executable** and not to the path of the folder where the tesseract executable is located, which is what you did.

Try this line instead:
`pytesseract.pytesseract.tesseract_cmd = '/usr/local/Cellar/tesseract/3.05.01/tesseract'`

Also be sure that you have the **tesseract executable** inside the folder.

**Comment by diyali03** [comment]
Thanks.
But the problem is that I build tesseract from Homebrew, 
I check the dir and it shows that : 
```
$  ls
AUTHORS			LICENSE			include
COPYING			NEWS			lib
ChangeLog		README.md		share
INSTALL_RECEIPT.json	bin
$ cd ..
$ ls
3.05.01
$ cd ..
$ ls
tesseract
```
Also, I try to set the path on: 
`/usr/local/Cellar/tesseract`
or
`/usr/local/Cellar/tesseract/3.05.01/share`
But it did work.

**Comment by diyali03** [comment]
May be I should try set the path to bin?

**Comment by int3l** [comment]
@diyali03 You can try to issue the following command in order to locate the path of tesseract:
`which tesseract`

**Comment by int3l** [comment]
Please reopen if you still have the issue.

**Comment by xxNB** [comment]
I have same problem

Traceback (most recent call last):
  File "/Users/zhangxin/project/crawl/douban/douban_spider/identify.py", line 25, in <module>
    return_word()
  File "/Users/zhangxin/project/crawl/douban/douban_spider/identify.py", line 22, in return_word
    return pytesseract.image_to_string(binaryImage, config='-psm 7')
  File "/Users/zhangxin/Desktop/py_3/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 122, in image_to_string
    config=config)
  File "/Users/zhangxin/Desktop/py_3/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

**Comment by xxNB** [comment]
I solved the problem by the way you  thank you

**Comment by liujunjie11** [comment]
--

**Comment by liujunjie11** [comment]
vi ~/.bash_profile

#tesseract
export PATH="/usr/local/Cellar/tesseract/4.0.0/bin:$PATH"

source ~/.bash_profile

tesseract_cmd = "/usr/local/Cellar/tesseract/4.0.0/bin/tesseract"

that's all!

**Comment by rathdebi** [comment]
how to check for tesseract executable in google colab. inline is my screenshot 
![image](https://user-images.githubusercontent.com/35034729/79696046-d4cb7e80-8297-11ea-8ffa-47ada49be446.png)

**Comment by snagargoje** [comment]
Same error as above in Colab Notebook. Any help would be appreciated.

<img width="912" alt="Screenshot 2021-12-17 at 5 51 42 PM" src="https://user-images.githubusercontent.com/10489094/146544505-503be03e-9ad2-43d6-84f6-159c64cc3ef9.png">

**Comment by yashwanth-sai-kanakala** [comment]
Please type "**Which Tesseract**" in the terminal which will provide the path of Tesseract executable. This resolved my error !
