### ISSUE TITLE
WindowsError: [Error 2] 

### ISSUE THREAD

**Issue by KyonP** [madmaze/pytesseract#64]
stuck in error.

```
python pytesseract.py test.png
Traceback (most recent call last):
  File "pytesseract.py", line 174, in <module>
    main()
  File "pytesseract.py", line 158, in main
    print(image_to_string(image))
  File "pytesseract.py", line 131, in image_to_string
    nice=nice)
  File "pytesseract.py", line 51, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "c:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2]
```
I think I've installed all the dependencies needed but can't solve this one.

**Comment by int3l** [comment]
Hello @KyonP, you should point pytesseract to the installation of Tesseract-OCR.
Please follow the documentation on the main page.
