### ISSUE TITLE
PermissionError: [WinError 5]

### ISSUE THREAD

**Issue by zh616110538** [madmaze/pytesseract#90]
I have changed Users's permission but it seems not work.
My python version is 3.5.4 installed by anaconda.How to solve this problem.
Traceback (most recent call last):
  File "F:/code/hello-world/python/opencv/OCR.py", line 11, in <module>
    print(pytesseract.image_to_string(Image.open("word.jpg",'r')),lang='chi_sim', config=tessdata_dir_config)
  File "D:\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "D:\Anaconda3\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "D:\Anaconda3\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda3\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
PermissionError: [WinError 5] 拒绝访问。

**Comment by int3l** [comment]
Hi @zh616110538 thanks for reporting the issue.
Did you follow the instructions in the README file?
Do you have the tesseract.exe installed?
What version and path do you have for it?

**Comment by int3l** [comment]
Closing since there is no clarification.
Please feel free to reopen.
