### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by hikmet-demir** [madmaze/pytesseract#99]
Hi
I'm trying to run pytesseract sample code but I stucked because of a stupid bug. 

```
my code:
try:
    import Image
except ImportError:
    from PIL import Image
import pytesseract

im = Image.open("12142369_1544586675763724_2096597599_n.jpg")

pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files (x86)\\Tesseract-OCR'

image = Image.open('12142369_1544586675763724_2096597599_n.jpg')

# Simple image to string
print(pytesseract.image_to_string(image, lang = 'tur'))

# Get bounding box estimates
print(pytesseract.image_to_boxes(Image.open('12142369_1544586675763724_2096597599_n.jpg')))

# Get verbose data including boxes, confidences, line and page numbers
print(pytesseract.image_to_data(Image.open('12142369_1544586675763724_2096597599_n.jpg')))

```
Error

> 
C:\Users\hkmet\Desktop\Somera Work\Text recognition>python first.py
Traceback (most recent call last):
  File "first.py", line 14, in <module>
    print(pytesseract.image_to_string(image, lang = 'tur'))
  File "C:\Users\hkmet\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\hkmet\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\hkmet\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\hkmet\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\hkmet\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Erişim engellendi
> 
Erişim engellendi = Permission denied

**Comment by int3l** [comment]
You're using incorrect tesseract_cmd path.
It should be ``C:\\Program Files (x86)\\Tesseract-OCR\\tesseract``

**Comment by hikmet-demir** [comment]
It worked, Ty so much!
Another question where can i load another language? It works for english for now but i need Turkish

**Comment by hikmet-demir** [comment]
I find it, ty
